### ISSUE TITLE
关于猫影视TV视频源的问题？

### ISSUE THREAD

**Issue by GD2021** [YuanHsing/freed#10]
![image](https://user-images.githubusercontent.com/81171294/151388811-f018b26b-ad37-4ed3-b750-6a567afac971.png)
为什么我用了您的规则，没法搜索呢？

**Comment by YuanHsing** [comment]
剛剛測試 可以搜尋

![Screenshot_20220127-232737](https://user-images.githubusercontent.com/17027880/151389753-fcc81ba9-4beb-4b17-85e0-98f94d89df8f.png)
