### ISSUE TITLE
猫影视为什么现在开始不提供直播源了呢？

### ISSUE THREAD

**Issue by hong26** [YuanHsing/freed#11]
怎么现在的电视直播的源都删除掉没更新了呢？

**Comment by YuanHsing** [comment]
直播源目前还是可以正常观看
所以请确认 猫影视TV是否更新到 2.09版本 (支援 "内置代理接口")

如果还是不能用的话,建议到底下TG频道逛逛!!
+ 猫影视TV 唐三 大佬 TG
https://t.me/mytangsan

+ 猫影视TV 官方TG (已转为公开群组)
https://t.me/catvodtv_offical

**Comment by xxj7527** [comment]
> 直播源目前还是可以正常观看 所以请确认 猫影视TV是否更新到 2.09版本 (支援 "内置代理接口")
> 
> 如果还是不能用的话,建议到底下TG频道逛逛!!
> 
> * 猫影视TV 唐三 大佬 TG
>   https://t.me/mytangsan
> * 猫影视TV 官方TG (已转为公开群组)
>   https://t.me/catvodtv_offical

你好 请问一下怎么群都没了 你清楚怎么回事吗 我没找到官方下载点和讨论的地方
