### ISSUE TITLE
custom_spider.jar的github.com地址，国内有时不能访问时断时续，如果觉得gitee.com需要手动同步麻烦，可以用以下三个网站，都可以自动同步

### ISSUE THREAD

**Issue by tomb003** [YuanHsing/freed#12]
https://notabug.org/
https://agit.ai/
这两个网站都可以设置自动同步，国内都可以访问，我一直用很久了，经测试很稳定。
如果嫌创建镜像麻烦，我已经创建好了，以下两个都是**每个小时**自动同步一次github.com/catvod/CatVodTVSpider：
https://notabug.org/tomb003/CatVodTVSpider
https://agit.ai/tomb003/CatVodTVSpider
希望能把custom_spider.jar用这两个网站的，别用github.com的了：
https://notabug.org/tomb003/CatVodTVSpider/raw/master/jar/custom_spider.jar
https://agit.ai/tomb003/CatVodTVSpider/raw/branch/master/jar/custom_spider.jar

另外，国内CSDN建立的https://gitcode.net/， 可以**每24小时**自动同步一次，我也建好了一个镜像：
https://gitcode.net/tomb003/CatVodTVSpider
https://gitcode.net/tomb003/CatVodTVSpider/-/raw/master/jar/custom_spider.jar

**Comment by YuanHsing** [comment]
谢谢你的建议及热心,有需要的话我会参考看看

如果你经常会遇到"有时不能访问时断时续"的情形的话
还是会建议你直接fork一份我的设定(maoo.json 或 maoo2.json)
然后再修改成你创建的custom_spider.jar

虽然会多花一些些时间 但对你来说应该是稳定比较重要
