### ISSUE TITLE
推荐一个iOS小说阅读

### ISSUE THREAD

**Issue by geekdmm0xff** [YuanHsing/freed#13]
蓝鲸阅读，可惜不支持阅读书源，目前只有美区可以下载。
https://apps.apple.com/cn/app/id1563610679
书源：https://gitee.com/dkreader/book-source-warehouse/raw/master/my.json

**Comment by YuanHsing** [comment]
感谢书友 推荐ios的阅读软体!!

**Comment by YuanHsing** [comment]
书源导入:
* 我的 > 书源管理 > 下一步 > 输入书源 https://gitee.com/dkreader/book-source-warehouse/raw/master/my.json > 完成 > 获取配置 > 共导入102个书源

简/繁切换:
* 我的 > 阅读设置 > 正文转换为繁体

书源切换:
* 发现 > 点取 右上角 左右键头 > 可切换 发现页书源

书籍搜索:
* 有 "搜索历史", 可一键清空
* 我的 > 阅读设置 > 可以开启 "多任务搜索" 

阅读介面
* 画面可以切换 "夜间/日间" 功能

就差 "WebDav云端备份" 及 "朗读" 功能了
能有"暗色主题" 的介面 好像也不错 哈哈
