### ISSUE TITLE
猫影视缝合接口的电视直播不可用

### ISSUE THREAD

**Issue by hong26** [YuanHsing/freed#14]
如题，好像直播配置的地址失效了。

**Comment by YuanHsing** [comment]
* "lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=aHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL1l1YW5Ic2luZy9PbmVDbGlja1J1bkBtYXN0ZXIveHBhdGgvbGl2ZS50eHQ="]}]}],
* aHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL1l1YW5Ic2luZy9PbmVDbGlja1J1bkBtYXN0ZXIveHBhdGgvbGl2ZS50eHQ=
* BASE64 解码
* https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/live.txt

直播配置的地址 Base64解碼的结果如上,正常!

建議 Fork ,然後自行修改直播地址
[Base64 在线编码解码](https://www.base64.pro/)

**Comment by YuanHsing** [comment]
如果你有在使用TG(Telegram)的話
建議可以到底下兩位大老的TG頻道逛逛
也可以改成他們維護的接口 試試直播
配置接口地址在他們的頻道裡面可以找到!
  + (非官方) 大佬维护接口1:[TG群](https://t.me/sdl6666)
  + (非官方) 大佬维护接口2:[TG群](https://t.me/colamint)

**Comment by hong26** [comment]
> * "lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=aHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL1l1YW5Ic2luZy9PbmVDbGlja1J1bkBtYXN0ZXIveHBhdGgvbGl2ZS50eHQ="]}]}],
> * aHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL1l1YW5Ic2luZy9PbmVDbGlja1J1bkBtYXN0ZXIveHBhdGgvbGl2ZS50eHQ=
> * BASE64 解码
> * https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/live.txt
> 
> 直播配置的地址 Base64解码的结果如上,可以正常浏览! 建议 Fork,然后自行修改直播地址
> 
> [Base64 在线编码解码](https://www.base64.pro/)



> * "lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=aHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL1l1YW5Ic2luZy9PbmVDbGlja1J1bkBtYXN0ZXIveHBhdGgvbGl2ZS50eHQ="]}]}],
> * aHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L2doL1l1YW5Ic2luZy9PbmVDbGlja1J1bkBtYXN0ZXIveHBhdGgvbGl2ZS50eHQ=
> * BASE64 解码
> * https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/live.txt
> 
> 直播配置的地址 Base64解码的结果如上,可以正常浏览! 建议 Fork,然后自行修改直播地址
> 
> [Base64 在线编码解码](https://www.base64.pro/)

你好，Base64解码后的链接（ https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/live.txt），这边用浏览器是打不开的。

**Comment by YuanHsing** [comment]
https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/live.txt

那就只剩下 我建议的方法 了
Fork我的配置, 然后换上你浏览器可以打开的网站的直播地址

---
直播格式:
"lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=你的直播地址(Base64编码格式)"]}]}],

示例:
1. 如果直播地址要改为 https://pastebin.com/raw/nfGmwSNg
2. 利用 [Base64 在线编码解码](https://www.base64.pro/) 
把上面的地址编码为Base64格式
3. 编码的结果为
aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L25mR213U05n
4. 置换猫设定
 "lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L25mR213U05n"]}]}],

**Comment by hong26** [comment]
> https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/live.txt
> 
> 那就只剩下 我建议的方法 了 Fork我的配置, 然后换上你浏览器可以打开的网站的直播地址
> 
> 直播格式: "lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=你的直播地址(Base64编码格式)"]}]}],
> 
> 示例:
> 
> 1. 如果直播地址要改为 https://pastebin.com/raw/nfGmwSNg
> 2. 利用 [Base64 在线编码解码](https://www.base64.pro/)
>    把上面的地址"编码"为Base64格式
> 3. 编码的结果为
>    aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L25mR213U05n
> 4. 置换猫设定
>    "lives":[{"group":"redirect","channels":[{"name":"live","urls":["proxy://do=live&type=txt&ext=aHR0cHM6Ly9wYXN0ZWJpbi5jb20vcmF3L25mR213U05n"]}]}],

知道怎么处理了，感谢，但接口里面（https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/）打不开，有很多链接需要替换稍微麻烦了点，有空了麻烦处理下，谢谢了。

**Comment by YuanHsing** [comment]
刚刚新增了 改过链接的配置接口

你把猫影视的配置接口,改成底下链接 测试看看
https://github.com/YuanHsing/freed/raw/master/maoo3.json

**Comment by hong26** [comment]
> 刚刚新增了 改过链接(含直播)的配置接口
> 
> 你把猫影视的配置接口,改成底下链接 测试看看 https://github.com/YuanHsing/freed/raw/master/maoo3.json

明白，知道怎么处理了，但

> > 
> 
> 方法一样,Fork我的另一配置,至你可以开启的网站, 如[Gitee](https://gitee.com/) 或 [Codeberg](https://codeberg.org/)?
> 
> XPath的设定全部存放在这 https://github.com/YuanHsing/OneClickRun
> 
> 自行修改 示例:
> 
> 待修改链接:
> 
> * https://cdn.jsdelivr.net/gh/YuanHsing/OneClickRun@master/xpath/360.json
> 
> 底下修改是基于你已经Fork我的配置为前提,修改上面的链接为私用
> 
> 1. 已Fork至 Gitee, 链接改成
>    https://gitee.com/hong26/OneClickRun/raw/master/xpath/360.json
> 2. 已Fork至 Codeberg, 链接改成
>    https://codeberg.org/hong26/OneClickRun/raw/master/xpath/360.json
> 3. 已Fork至 Github, 链接改成
>    https://github.com/hong26/OneClickRun/raw/master/xpath/360.json

是的，目前只能这么处理了，谢谢。jsdelivr.net墙内也确实解析不了了，真的郁闷。
