### ISSUE TITLE
关于猫影XB搜寻卡顿的问题

### ISSUE THREAD

**Issue by xiaohc666** [YuanHsing/freed#15]
大佬，之前猫影视在2.1.0.5用XB规则时搜索会出现卡顿或卡死的情况，我逐个排查后，发现是23影院这个源的问题，不知道是站点的问题还是json的问题，屏蔽掉这个源就解决了，后来升级到2.11b4，没有出现卡死情况，启用23影院尝试，结果搜出来的这个站点的全是空名称，所以卡顿还是个别源的问题，跟限制搜寻结果为5关系应该不大，打个比方，假如这么限制，我要模糊搜索"向往的生活"，因为它的版本多，而且很多季，我其实想看的是"向往的生活第四季加长版"，是不是就表示现在的规则可能搜不到我想要的结果？除非我能完完整整写出片名？

**Comment by YuanHsing** [comment]
感谢猫友回报
* "23影院" 搜寻结果空白多行的问题，刚好我今天更新XBiubiu源时有发现,已经把导致搜寻错误的问题一并修正了!
* "搜寻限制"我也已经全部修改回之前的预设值500了

经测试：
* 搜寻 "向往的生活"，虽然搜寻结果可能上千，但等到全部搜寻结束，猫影视依然妥妥的!
* 已排除 搜寻结果的数量 会导致 猫影视卡顿

所以 "23影院.json" 原本的错误搜寻代码才是导致卡顿的主因
感谢猫友指正!
