### ISSUE TITLE
maooxp.json

### ISSUE THREAD

**Issue by taoqixfz** [YuanHsing/freed#16]
请教一下怎么直接在猫影视TV接口中直接使用maooxp.json的链接，我发现基本上都删库了
为什么我弄到接口里面报错不能用呢

**Comment by YuanHsing** [comment]
建议方法：
直接FORK一份我的设定，然后配置接口的格式如下(二选一)
* Github 接口名称 格式1:
	* https://github.com/taoqixfz/freed/raw/master/maoo.json

* Github 接口名称 格式2:
	* https://raw.githubusercontent.com/taoqixfz/freed/master/maooxp.json

---
或是直接用我的设定当配置接口(二选一)
* Github 接口名称 格式1:
	* https://github.com/YuanHsing/freed/raw/master/maoo.json

* Github 接口名称 格式2:
	* https://raw.githubusercontent.com/YuanHsing/freed/master/maooxp.json

**Comment by taoqixfz** [comment]
> 建议方法： 直接FORK一份我的设定，然后配置接口的格式如下(二选一) (fork的好处是 你可以依照你的需求,再去修改maooxp.json的内容)
> 
>     * Github 接口名称 格式1:
>       
>       * https://github.com/taoqixfz/freed/raw/master/maooxp.json
> 
>     * Github 接口名称 格式2:
>       
>       * https://raw.githubusercontent.com/taoqixfz/freed/master/maooxp.json
> 
> 
> 或是直接用我的设定当配置接口(二选一)
> 
>     * Github 接口名称 格式1:
>       
>       * https://github.com/YuanHsing/freed/raw/master/maooxp.json
> 
>     * Github 接口名称 格式2:
>       
>       * https://raw.githubusercontent.com/YuanHsing/freed/master/maooxp.json

直接用报错是咋肥四？

**Comment by YuanHsing** [comment]
> 直接用报错是咋肥四？

或许跟你的梯子有关系
我刚刚上传了测试用的 免梯子 配置接口
再请猫友帮忙测试看看是否可正常运作(含电视直播)

CH猫友 免梯子 测试配置接口:
* https://freed.yuanhsing.cf/maoocf.json

**Comment by sclodestar** [comment]
大佬，请问一下，custom_spider.jar是用什么生成的？里面需要配置吗？用什么工具配置？

在夸夸群里面有不少的jar，这些jar通用吗？谢谢

**Comment by YuanHsing** [comment]
> 大佬，请问一下，custom_spider.jar是用什么生成的？里面需要配置吗？用什么工具配置？
> 
> 在夸夸群里面有不少的jar，这些jar通用吗？谢谢

Github Actions 可以先大概的去了解一下
* 我是直接fork小黄瓜大佬的[CatVodTVSpider](https://github.com/YuanHsing/CatVodTVSpider),但现在瓜佬已经删库了
* 官方仓库 跟 小黄瓜大佬的仓库 差在瓜佬还有另外新增了Xbiubiu.java 跟 LittleApple.java, 也就是多了支援Biubiu的格式及可以看小苹果的规则.我仓库里的XBiubiuLA2.jar就是这样生成的
* 但是,优化Xbiubiu 及 新增Kuaikan规则的XBiubiuLA3.jar 则是直接转自瓜佬放出的链接,当时瓜佬已删库,所以自然就没有优化过的Xbiubiu.java及Kuaikan.java 的源码

利用Github Actions自动生成JAR
* 自动生成JAR所需的 genJar.yml ,仓库已有,所以只需要很简单的点点按钮,JAR就会自动生成在 jar 的目录里了
* 自动生成JAR： Actions --> Spider Jar Gen CI --> Run workflow --> Run workflow --> 等几分钟 -->  等转动的黄色圆圈 变成 打勾的绿色圆圈  --> 去 jar目录确认刚刚生成的 custom_spider.jar

电脑端 可以浏览JAR的程式
* [Jadx](https://github.com/skylot/jadx/releases)  --> 下载
* 浏览JAR 路径： 原始码 --> com.github.catvod --> spider
* 同时,你大概就会知道这个JAR里有哪些配置,接口该怎样写了

题外话
* 不会写JAVA或缝合JAR，还不如直接捡别人缝合好的JAR用，比较快!
* 但接口配置自定义倒是可以学习一下，因应猫TV的新统计后台(每周传播超5k ip的配置地址会被封)，所以这几天"本地接口配置"的讨论还蛮热门的

**Comment by sclodestar** [comment]
> 

收悉，谢谢大佬非常仔细的教学，我也是看issue慢慢学着fork 到fastgit的使用。不过webserver我有一堆，私用的话，@sc_lodestar吧

**Comment by sclodestar** [comment]
tg哈

**Comment by YuanHsing** [comment]
> > 
> 
> 收悉，谢谢大佬非常仔细的教学，我也是看issue慢慢学着fork 到fastgit的使用。不过webserver我有一堆，私用的话，@sc_lodestar吧

哈哈 先谢过猫友了!

猫影视TV至 2.1.1 Beta5，TG已开放下载了
* Add local protocol clan:// support.

瓜佬刚刚正在线上教学，热烈讨论中，赶快去学学!!
官方正在慢慢的把使用者导向使用"本地接口配置"，所以web server以后应该也用不太到了才对!

**Comment by YuanHsing** [comment]
猫影视TV 2.1.1 Beta5 刚刚又更新了
2.1.1Beta5版本已弃用custom_spider.jar的读取，本地请配合clan://协议测试
猫大、猫小弟威武！

* Add local protocol clan:// support.
* 设置界面增加除存权限获取按钮
* 优化扫码设置网页展示
* 弃用sdcard根目录custom_spider.jar读取支持
