### ISSUE TITLE
大佬好，请教一个关于视频分类获取的问题。

### ISSUE THREAD

**Issue by Sturiss** [YuanHsing/freed#18]
一直想学习拿到一个视频网站，如何确认网站里的视频的地址？不知从何入手呢

**Comment by Sturiss** [comment]
![image](https://user-images.githubusercontent.com/106640910/172978671-185da51b-233f-4a43-b08e-65596ade7da5.png)
这个修改，是根据啥确定的字符变了呢？

**Comment by YuanHsing** [comment]
> ![image](https://user-images.githubusercontent.com/106640910/172978671-185da51b-233f-4a43-b08e-65596ade7da5.png) 这个修改，是根据啥确定的字符变了呢？

[哔嘀影视](https://bidiys.cc/)
* 动漫 --> 影片库 --> 日本番剧片库  --> 这时的网址 --> https://bidiys.cc/vodshow-rbdm-----------.html
* 最底下页码点选2(随便一页都可以) --> 这时的网址 --> https://bidiys.cc/vodshow-rbdm--------2---.html
* 页码2之前 的 /vodshow-rbdm--------  --> 就是分类的网址了 --> 日本番剧$/vodshow-rbdm--------#
* 页码2之后 的 ---.html --> 就是houzhui要设定的值了 --> "houzhui": "---.html",

**Comment by YuanHsing** [comment]
> 一直想学习拿到一个视频网站，如何确认网站里的视频的地址？不知从何入手呢

目前 XBiubiu的规则比较简单,(更新.导演.演员.简介 都可以跳过不用设定)
* 模版参考:[🥒自定义接口模板.txt](https://github.com/YuanHsing/OneClickRun/raw/master/MeowXB/%F0%9F%A5%92%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A5%E5%8F%A3%E6%A8%A1%E6%9D%BF.txt)

XBiubiu规则写好之后,配置接口内容设定：
{"key":"csp_biubiu_随便取不要重复","name":"🥒随便取不要重复(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://XBiubiu规则存放路径/XBiubiu规则.json"},

**Comment by Sturiss** [comment]
这个规则这个 json下载不下来，应该是链接多选了2个字符，麻烦您再看看，谢谢。是xbiubiu规则，xpath规则 讲解参考么？

**Comment by Sturiss** [comment]
> > ![image](https://user-images.githubusercontent.com/106640910/172978671-185da51b-233f-4a43-b08e-65596ade7da5.png) 这个修改，是根据啥确定的字符变了呢？
> 
> [哔嘀影视](https://bidiys.cc/)
> 
> * 动漫 --> 影片库 --> 日本番剧片库  --> 这时的网址 --> https://bidiys.cc/vodshow-rbdm-----------.html
> * 最底下页码点选2(随便一页都可以) --> 这时的网址 --> https://bidiys.cc/vodshow-rbdm--------2---.html
> * 页码2之前 的 /vodshow-rbdm--------  --> 就是分类的网址了 --> 日本番剧$/vodshow-rbdm--------#
> * 页码2之后 的 ---.html --> 就是houzhui要设定的值了 --> "houzhui": "---.html",

回复效率真高，非常感谢，学习了！

**Comment by Sturiss** [comment]
另外，“打驴动漫”更新推荐不能加载呢，还有  “厂长资源-蓝光 ”也是不能显示更新推荐，是本身没有跟新推荐呢，还是没有写入代码？还是哪里的情况呢？如果是没写入代码，那么更新推荐哪里应该如何写呢？

**Comment by YuanHsing** [comment]
> 
xpath语法 了解一下
* https://www.w3school.com.cn/xpath/index.asp

网页快速查询XPATH的方法：
* chrome 浏览器 --> 按F12 --> 右侧视窗 --> 对你想要查询的元素按滑鼠右键 --> 复制 XPATH 或 复制XPATH完整路径

**Comment by YuanHsing** [comment]
> 这个规则这个 json下载不下来，应该是链接多选了2个字符，麻烦您再看看，谢谢。是xbiubiu规则，xpath规则 讲解参考么？

[🥒自定义接口模板.txt](https://github.com/YuanHsing/OneClickRun/raw/master/MeowXB/%F0%9F%A5%92%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A5%E5%8F%A3%E6%A8%A1%E6%9D%BF.txt)
内容如下，全部复制 然后贴到自己的文件吧
---

{
  "author": "",
  "name": "自定义规则讲解演示",
  "url": "https://xxx.com", //填网站链接
  "tihuan": "cnzz.com", //这个不用动，是个别网站嗅探时过滤地址用的
  "User": "空", //这个不用动，是个别网站播放需要请求头时才用到
  //"User": "User-Agent:Dart/2.14 (dart:io)",
  //"shouye": "1",

  "fenlei": "电影$/index.php/vod/show/id/1/page/#电视剧$/index.php/vod/show/id/2/page/#综艺$/index.php/vod/show/id/3/page/#动漫$/index.php/vod/show/id/4/page/#记录$/index.php/vod/show/id/5/page/#国产剧$/index.php/vod/show/id/201/page/#港台剧$/index.php/vod/show/id/202/page/#日韩剧$/index.php/vod/show/id/203/page/#欧美剧$/index.php/vod/show/id/204/page/#海外剧$/index.php/vod/show/id/205/page/", //网站列表的分类
  "houzhui": ".html", //网站翻页链接的后缀

  "shifouercijiequ": "0", //截取的列表数组是否需要二次截取，0不需要，1需要
  "jiequqian": "空", //不需要二次截取就填空
  "jiequhou": "空", //不需要二次截取就填空
  "jiequshuzuqian": "class=\"pic\"", //截取的列表数组的前关键词,截取的关键词有 " 的用 \ 进行转义
  "jiequshuzuhou": "</li>", //截取的列表数组的后关键词,截取的关键词有 " 的用 \ 进行转义
  "tupianqian": "data-original=\"", //列表中资源的图片前关键词,截取的关键词有 " 的用 \ 进行转义
  "tupianhou": "\"", //列表中资源的图片后关键词,截取的关键词有 " 的用 \ 进行转义
  "biaotiqian": "title=\"", //列表中资源的标题前关键词,截取的关键词有 " 的用 \ 进行转义
  "biaotihou": "\"", //列表中资源的标题后关键词,截取的关键词有 " 的用 \ 进行转义
  "lianjieqian": "href=\"", //列表中资源的详情页跳转链接前关键词,截取的关键词有 " 的用 \ 进行转义
  "lianjiehou": "\"", //列表中资源的详情页跳转链接后关键词,截取的关键词有 " 的用 \ 进行转义

  //搜索部分基本不用动，现在网站基本都是苹果CMS，所有搜索是固定的。
  "sousuoqian": "/index.php/ajax/suggest?mid=1&wd=",
  "sousuohou": "&limit=500",
  "sousuohouzhui": "/index.php/vod/detail/id/", //搜索页影片跳转详情页的中间标识链接部分
  "ssmoshi": "0",
  "sousuoshifouercijiequ": "0",
  "jspic": "pic",
  "jsname": "name",
  "jsid": "id",
  "ssjiequqian": "空",
  "ssjiequhou": "空",
  "ssjiequshuzuqian": "空",
  "ssjiequshuzuhou": "空",
  "sstupianqian": "空",
  "sstupianhou": "空",
  "ssbiaotiqian": "空",
  "ssbiaotihou": "空",
  "sslianjieqian": "空",
  "sslianjiehou": "空",

  "bfshifouercijiequ": "0",
  "bfjiequqian": "空",
  "bfjiequhou": "空",
  "bfjiequshuzuqian": "id=\"zu", //播放截取的列表数组的前关键词
  "bfjiequshuzuhou": "</ul>", //播放截取的列表数组的后关键词

  "zhuangtaiqian": "更新：</span>", //状态前关键词
  "zhuangtaihou": "</p>", //状态后关键词
  "daoyanqian": "导演：</span>", //导演前关键词
  "daoyanhou": "</p>", //导演态后关键词
  "zhuyanqian": "主演：</span>", //主演前关键词
  "zhuyanhou": "</p>", //主演后关键词
  "juqingqian": "简介：</span>", //剧情前关键词
  "juqinghou": "</div>", //剧情后关键词

  "bfyshifouercijiequ": "0", //截取的播放列表数组是否需要二次截取，0不需要，1需要
  "bfyjiequqian": "空", //不需要二次截取就填空
  "bfyjiequhou": "空", //不需要二次截取就填空
  "bfyjiequshuzuqian": "<a", //播放剧集数组前关键词
  "bfyjiequshuzuhou": "/a>", //播放剧集数组后关键词
  "bfbiaotiqian": ">", //播放剧集标题前关键词
  "bfbiaotihou": "<", //状播放剧集标题后关键词
  "bflianjieqian": "href=\"", //播放剧集链接前关键词
  "bflianjiehou": "\""
} //播放剧集链接后关键词

**Comment by YuanHsing** [comment]
> 另外，“打驴动漫”更新推荐不能加载呢，还有 “厂长资源-蓝光 ”也是不能显示更新推荐，是本身没有跟新推荐呢，还是没有写入代码？还是哪里的情况呢？如果是没写入代码，那么更新推荐哪里应该如何写呢？

* “打驴动漫”更新推荐???
  "fenlei": "热门新番$/index.php/vod/show/id/23/page/#日本动漫$/index.php/vod/show/id/21/page/#国产动漫$/index.php/vod/show/id/22/page/#欧美动漫$/index.php/vod/show/id/25/page/#动漫电影$/index.php/vod/show/id/24/page/#剧集$/index.php/vod/show/id/27/page/#电影$/index.php/vod/show/id/28/page/#综艺$/index.php/vod/show/id/31/page/", //网站列表的分类

*  “厂长资源-蓝光 ”更新推荐???
  "fenlei": "本月热门$/benyueremen/page/#高分影视$/gaofenyingshi/page/#豆瓣电影TOP250$/dbtop250/page/#最新电影$/zuixindianying/page/#电视剧$/dsj/page/#国产剧$/gcj/page/#美剧$/meijutt/page/#韩剧$/hanjutv/page/#日剧$/movie_bt_series/rj/page/#海外剧$/movie_bt_series/hwj/page/#番剧$/fanju/page/#动漫$/dm/page/#韩国电影$/movie_bt_series/hanguodianying/page/#纪录片$/movie_bt/movie_bt_tags/jlpp/page/",

你说的"更新推荐"是哪一个??
贴网址我看看
如果是原本如上面的"fenlei"设定，我都有测过，应该都没有问题，每个分类都可以正常显示

**Comment by YuanHsing** [comment]
另外，如果你是全部XBiubiu系列都不能看的话
我会建议你
* 猫影视TV更新到 2.1.1 Beta5，已经直接支援"本地配置接口" clan:// 了，可以去TG频道看看学学!
* 或是直接用我的 CH猫友测试配置接口
  * https://freed.yuanhsing.cf/maoocf.json

**Comment by Sturiss** [comment]
![image](https://user-images.githubusercontent.com/106640910/172999338-3d4197dc-b747-40d2-a96c-751cd83036f0.png)
刚才又试了下这两个站点，居然又都能显示出来了。不知为何   非常感谢！

**Comment by YuanHsing** [comment]
> ![image](https://user-images.githubusercontent.com/106640910/172999338-3d4197dc-b747-40d2-a96c-751cd83036f0.png) 刚才又试了下这两个站点，居然又都能显示出来了。不知为何 非常感谢！

原来你指的是 猫影视的首页
那也是参数设定的，如下

把 //"shouye": "1",  --> 改成 "shouye": "1",

就会显示首页的"更新推荐"了"

**Comment by Sturiss** [comment]
> > 一直想学习拿到一个视频网站，如何确认网站里的视频的地址？不知从何入手呢
> 
> 目前 XBiubiu的规则比较简单,(更新.导演.演员.简介 都可以跳过不用设定)
> 
> * 模版参考:[🥒自定义接口模板.txt](https://github.com/YuanHsing/OneClickRun/raw/master/MeowXB/%F0%9F%A5%92%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A5%E5%8F%A3%E6%A8%A1%E6%9D%BF.txt)
> 
> XBiubiu规则写好之后,配置接口内容设定： {"key":"csp_biubiu_随便取不要重复","name":"🥒随便取不要重复(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"[https://XBiubiu规则存放路径/XBiubiu规则.json"}](https://XBiubiu%E8%A7%84%E5%88%99%E5%AD%98%E6%94%BE%E8%B7%AF%E5%BE%84/XBiubiu%E8%A7%84%E5%88%99.json%22%7D),

“https://XBiubiu规则存放路径/XBiubiu规则.json”   这个文件下载不了，不能打开，看不到xbiubiu规格。

**Comment by YuanHsing** [comment]
> ![image](https://user-images.githubusercontent.com/106640910/172999338-3d4197dc-b747-40d2-a96c-751cd83036f0.png) 刚才又试了下这两个站点，居然又都能显示出来了。不知为何 非常感谢！

有设定 "shouye": "1",
然后有时后显示 有时后不显示

也有可能是加载首页的时间逾时了 所以直接跳过 避免卡无限读取首页
之前好像有猫友就一直卡在读取首页，等了10分钟也还没有加载出来
所以 猫影视 2.1.1 Beta4版本 就有修正 add home page load timeout

**Comment by YuanHsing** [comment]
> > > 一直想学习拿到一个视频网站，如何确认网站里的视频的地址？不知从何入手呢
> > 
> > 
> > 目前 XBiubiu的规则比较简单,(更新.导演.演员.简介 都可以跳过不用设定)
> > 
> > * 模版参考:[🥒自定义接口模板.txt](https://github.com/YuanHsing/OneClickRun/raw/master/MeowXB/%F0%9F%A5%92%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A5%E5%8F%A3%E6%A8%A1%E6%9D%BF.txt)
> > 
> > XBiubiu规则写好之后,配置接口内容设定： {"key":"csp_biubiu_随便取不要重复","name":"🥒随便取不要重复(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"[https://XBiubiu规则存放路径/XBiubiu规则.json"}](https://XBiubiu%E8%A7%84%E5%88%99%E5%AD%98%E6%94%BE%E8%B7%AF%E5%BE%84/XBiubiu%E8%A7%84%E5%88%99.json%22%7D),
> 
> “[https://XBiubiu规则存放路径/XBiubiu规则.json”](https://XBiubiu%E8%A7%84%E5%88%99%E5%AD%98%E6%94%BE%E8%B7%AF%E5%BE%84/XBiubiu%E8%A7%84%E5%88%99.json%E2%80%9D) 这个文件下载不了，不能打开，看不到xbiubiu规格。

这只是一个范例
教你把写好的Xbiubiu规则 添加 到你自己的接口配置json里面
譬如 我今天写了一个 独播库.json 的 Xbiubiu规则
那
接口的配置可以改成如下设置：
{"key":"csp_biubiu_独播库","name":"🥒独播库(XB)","type":3,"api":"csp_XBiubiu","searchable":1,"quickSearch":1,"filterable":0,"ext":"https://www.123.456/独播库.json"},

**Comment by Sturiss** [comment]
理解了，现在试试找个网站 来自己谢谢看。是不是所有视频网站都可以用xbiubiu规则来写，或者用xpath规则来写？着用啥规则是不是需要jar决定？

**Comment by YuanHsing** [comment]
> 理解了，现在试试找个网站 来自己谢谢看。是不是所有视频网站都可以用xbiubiu规则来写，或者用xpath规则来写？着用啥规则是不是需要jar决定？

我的话，是会先利用猫影视的"推送" 这个功能，先测试网页的内容能不能被自动嗅探播放，不能自动播放成功的话，就放弃那个网站了

* 随便复制网站的任一集数的链接
 * 譬如我今天要测试 "打驴动漫"的"一拳超人"的"第01集"的链接
  https://www.dqsj.cc/index.php/vod/play/id/423/sid/2/nid/1.html  --> 记得先复制链接
 * 猫影视TV --> 推送 --> 推送剪贴板内容
 * 如果可以成功在猫影视推送并成功播放，那"打驴动漫"这个网站就适用XBiubiu的规则

**Comment by YuanHsing** [comment]
忘记讲最重要的，很不巧的
如果你用的是底下我的配置接口其中之一：
* [maoocf.json](https://github.com/YuanHsing/freed/blob/master/maoocf.json)

* [maoocf2.json](https://github.com/YuanHsing/freed/blob/master/maoocf2.json)
* [maooxp.json](https://github.com/YuanHsing/freed/blob/master/maooxp.json)

* [maooxp2.json](https://github.com/YuanHsing/freed/blob/master/maooxp2.json)

全部不支援"推送"这一功能，因为 XBiubiuLA3.jar 包里少了PushAgent这个Class
所以你必须要先fork我的设定，然后再手动修改上面任一你使用的配置接口的spider设定

---
01.先找到如下内容(配置显示目前spider使用的是XBiubiuLA3.jar)

#套Biubiu+LiteApple+七七+PushAgent规则
//"spider":"https://oneclickrun.yuanhsing.cf/MeowXB/XBiubiuLA2.jar",
#套Biubiu修正+LiteApple+Kuaikan规则 (没有PushAgent)
"spider":"https://oneclickrun.yuanhsing.cf/MeowXB/XBiubiuLA3.jar",

---
02.然后改成跟底下一样，spider更换成XBiubiuLA2.jar就可以了
XBiubiuLA2.jar 支援 推送 功能

#套Biubiu+LiteApple+七七+PushAgent规则
"spider":"https://oneclickrun.yuanhsing.cf/MeowXB/XBiubiuLA2.jar",
#套Biubiu修正+LiteApple+Kuaikan规则 (没有PushAgent)
//"spider":"https://oneclickrun.yuanhsing.cf/MeowXB/XBiubiuLA3.jar",

**Comment by Sturiss** [comment]
非常感谢，在我的理解里 A3应该是A的升级，呵呵 ，如果按照您说的改成了A2的话，是不是对应的json里的有些站点就不能用了？

**Comment by Sturiss** [comment]
非常感谢，在我的理解里 A3应该是A2的升级，呵呵 ，如果按照您说的改成了A2的话，是不是对应的json里的有些站点就不能用了？

**Comment by YuanHsing** [comment]
> 非常感谢，在我的理解里 A3应该是A2的升级，呵呵 ，如果按照您说的改成了A2的话，是不是对应的json里的有些站点就不能用了？

如上注释说明，只有 快看(Kuaikan) 跟 七七(Kunyu77) 会有影响...
建议"取消注解//",全开就好了 省事事省!


---
#套Biubiu+LiteApple+七七+PushAgent规则
"spider":"https://oneclickrun.yuanhsing.cf/MeowXB/XBiubiuLA2.jar",

当spider为XBiubiuLA2.jar时，"快看"不能看，"七七"可以看

//{"key":"csp_Kuaikan","name":"🎈快看(SP)","type":3,"api":"csp_Kuaikan","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_LiteApple","name":"🍎小苹果(SP)","type":3,"api":"csp_LiteApple","searchable":1,"quickSearch":1,"filterable": 1},
{"key":"csp_Kunyu77","name":"七七(SP)","type":3,"api":"csp_Kunyu77","searchable":1,"quickSearch":1,"filterable":1},

---
#套Biubiu修正+LiteApple+Kuaikan规则 (没有PushAgent)
"spider":"https://oneclickrun.yuanhsing.cf/MeowXB/XBiubiuLA3.jar",

当spider为XBiubiuLA3.jar时，"快看"可以看，"七七"不能看

{"key":"csp_Kuaikan","name":"🎈快看(SP)","type":3,"api":"csp_Kuaikan","searchable":1,"quickSearch":1,"filterable":1},
{"key":"csp_LiteApple","name":"🍎小苹果(SP)","type":3,"api":"csp_LiteApple","searchable":1,"quickSearch":1,"filterable": 1},
//{"key":"csp_Kunyu77","name":"七七(SP)","type":3,"api":"csp_Kunyu77","searchable":1,"quickSearch":1,"filterable":1},

**Comment by Sturiss** [comment]
好的，我本来也就懂点皮毛，所以问题比较多，经过您的讲解，对猫理解跟深入了，不过真是不好意思，今天麻烦您一天了；另外XBiubiuLA3.jar/XBiubiuLA2jar是不对外分享的吧？有没有能供学习研究的jar源码呢？

**Comment by YuanHsing** [comment]
> 好的，我本来也就懂点皮毛，所以问题比较多，经过您的讲解，对猫理解跟深入了，不过真是不好意思，今天麻烦您一天了；另外XBiubiuLA3.jar/XBiubiuLA2jar是不对外分享的吧？有没有能供学习研究的jar源码呢？

另一issue有提及 参考一下
https://github.com/YuanHsing/freed/issues/16#issuecomment-1151867402

**Comment by YuanHsing** [comment]
猫影视TV 官方Github 有详细的 XPATH 套娃规则
https://github.com/catvod/CatVodTVSpider/blob/master/XPath.md

**Comment by Sturiss** [comment]
clan:// support. 这个命名如何使用呢？比如我把1.json文件放在了局域网一台计算机（IP：192.168.1.100）如下目录下："C:\Users\1.json" ，哪么在猫主页接口上如何填写呢？

**Comment by YuanHsing** [comment]
> clan:// support. 这个命名如何使用呢？比如我把1.json文件放在了局域网一台计算机（IP：192.168.1.100）如下目录下："C:\Users\1.json" ，哪么在猫主页接口上如何填写呢？

* clan://
  * 适用于单一设备(手机、电脑或盒子)，然后把别人已建好的所有目录&设定全部拉到设备的本地目录下，最后再去设定配置接口(1.json)的路径，甚至(1.json)这个文件的设定里的路径也都一并要改
  * 目前猫群大致的做法：
  * 先下载猫友分享已打包好的maomao.zip --> 根目录解压缩 --> 然后透过扫码或浏览器访问网址 --> 设置配置接口
  * 至于配置接口文件里的路径设定，猫友已经都改好了，所以不用去改
  * 配置接口 设定好后，基本上就可以开始使用了

---
但你的情况似乎是
一至多台安装猫影视的设备或计算机，要同时去读取局域网内的某一台计算机的1.json文件
如果是这样子 就不适用 以 clan://  的方式设定配置接口

这时候你会碰到的问题是 1.json文件的共享方式及路径：
* 192.168.1.100这台电脑 如果是透过windows文件共享的方式共享1.json，那电脑共享路径如何设定?
* 192.168.1.100这台电脑 如果是透过web server的方式共享1.json，那局域网路径该如何设定?

如果上面都不懂的话，那我还是会建议你使用比较简单的方式
就跟以前一样直接把配置文件丢在网路上，然后配置接口的设定的格式也是跟以前一样，如 http://github.com/1.json

---
建议你：
* 直接跳过 clan:// ，还不如继续使用以前的配置接口设定 (http://github.com/123456.json) 来的方便

如果还是想要玩看看新功能 clan://
* 先去猫TG群 学习学习，目前 clan:// 的话题还很热门，会有很多热心的猫友帮忙
  * 下载懒人包 maomao.zip，然后把 clan:// 这种格式的配置接口成功的设定，且可以顺利地在本地端使用
  * 尝试添加新的接口配置文件并下载存放到本地端的目录，并试着修改"配置接口的内容&路径"，且可以成功的在本地端使用
  * 要学要快 猫群每天清文 也许明天教学文 就被清掉了

**Comment by Sturiss** [comment]
猫TG群 怎们进入？
没找到 呵呵

**Comment by YuanHsing** [comment]
> 猫TG群 怎们进入？ 没找到 呵呵

我的每一个配置接口里面都有写的说
# TG (猫影视TV渡口🛳, 不定期开放邀请链接 )
https://t.me/catvodtv_offical

* 先加这个TG
* 当猫大下次再开放加群组的时后，会发送加入群组链接
* 目前能做的只有等再次开放了
