### ISSUE TITLE
大佬好，梨园行戏曲这个app的源，咱们有办法把源搞到猫源里去么？

### ISSUE THREAD

**Issue by Sturiss** [YuanHsing/freed#19]
![image](https://user-images.githubusercontent.com/106640910/173477039-5ad535d1-bb7e-4d73-9cb8-431e62cb0204.png)

**Comment by YuanHsing** [comment]
APP源的话
建议可以去猫影视TV的TG群问问看，大佬很多 也许会有人帮你解答

**Comment by yoyo82520** [comment]
YuanHsing ***@***.***> 于 2022年6月14日周二 上午9:21写道：
