### ISSUE TITLE
大佬，293解析失效了，

### ISSUE THREAD

**Issue by solo052** [YuanHsing/freed#20]
大佬，293解析失效了，

**Comment by YuanHsing** [comment]
这位猫友 请问一下
你用的是哪一种配置接口
懒人包 还是 线上的配置接口(meow meow2 meowcf mowcf2)??

如果是懒人包
你可以把配置里的这一行删除即可
{"name":"293","type":1,"url":"http://81.71.48.249:4456/jsonc/longxia.php?url=","ext":{"flag":["qq","qiyi","mgtv","youku","letv","sohu","xigua","1905"],"header":{"User-Agent":"Dart/2.14 (dart:io)"}}},

另外，给你参考一下
唐三大佬的懒人包的 "360"网站 用293解析特别快
刚刚测试，也还能用

还有，现在配置一大堆不用解析就可以看的网站
建议看那些不需解析的网站就够用了

猫友所浏览 需要解析的网站名称 可以顺便留言跟我说一下

**Comment by solo052** [comment]
解决了，谢谢大佬。我用的是bd懒人包。里面的360可以用。
