### ISSUE TITLE
请教个githbu网站的使用问题，谢谢！

### ISSUE THREAD

**Issue by Sturiss** [YuanHsing/freed#21]
不知道如何建目录，如下图tv，mobile等，能方便指教下么 感谢。
![image](https://user-images.githubusercontent.com/106640910/174421853-1de3e466-811d-49f7-b0c8-39269299b547.png)

**Comment by YuanHsing** [comment]
https://blog.csdn.net/Maiduoudo/article/details/101061643

**Comment by YuanHsing** [comment]
https://www.youtube.com/watch?v=iwaGwjRINGI
