### ISSUE TITLE
请问大佬你的猫接口怎么导入猫影视

### ISSUE THREAD

**Issue by king4107** [YuanHsing/freed#3]
请问大佬你的猫接口怎么导入猫影视

**Comment by YuanHsing** [comment]
可利用 https://netcut.cn/ 这个网站

1.输入自己喜欢的剪贴版名称
> 查看剪贴版 > 贴上maoo或maoo2全部内容 > 左上角「有效期」改为三年 > 然后产生「只读链接」

2.猫影视TV的 设置 > 当前配置接口 > 粘贴上刚刚产生的「只读链接」> 确定

这样子就会有一个你专用的接口了！

猫影视TV作者的github及TG交流群
https://github.com/catvod/CatVodTVSpider
https://t.me/catvodtv

**Comment by king4107** [comment]
谢谢大佬，再问下maoo和maoo2区别在哪里

**Comment by YuanHsing** [comment]
> 谢谢大佬，再问下maoo和maoo2区别在哪里
底下是之前的回覆，可以了解一下！哈

[后面带2的源和不带2的有什么区别？？ #1](https://github.com/YuanHsing/freed/issues/1)

[大佬能否做个2.04完整配置文件，现在的文件复制后任何影视源主页无法显示 #2](https://github.com/YuanHsing/freed/issues/2)
