### ISSUE TITLE
感谢大佬分享的自行车和汽车json

### ISSUE THREAD

**Issue by cnnbgo** [YuanHsing/freed#4]
大佬有实力就把福利diy101破了吧，墙内源，速度快，片库大🤗

**Comment by cnnbgo** [comment]
弄到猫影视tv源里面，可能需要反编译他们的apk，具体我不懂。成功了这将是一个非常了不起的福利源，秒杀一众小作坊的源。

**Comment by YuanHsing** [comment]
哎呀 你太看得起我了!
我真的只会 Ctrl+C 跟 Ctrl+V , 福利源也都是从其他软体里搜集过来之后再整理过的而已!!
