### ISSUE TITLE
猫影视TV的问题

### ISSUE THREAD

**Issue by ThorJsbox** [YuanHsing/freed#5]
您好，因为没有您的联系方式，就这样留言给您了，想向您请教学习几个关于猫影视TV的问题。

一、就是如何生动自己的main_spider.txt或者main_spider.jar这个文件，我去catvod的github库那里下载了源码，然后用Android Studio打开，找到spider文件夹，下面很多JAVA文件，教程上应该就是在这里修改，但我没看懂，应该修改哪里，是添加新的文件或是内容，还是删除失效的文件或是内容，还是在哪个文件修改里就可以,很疑惑，这里请求去惑。

二、关于首页数据源。您的是2345源，默认的好像是素白白，这个应该也是这个main_spider.txt（jar）决定的，这好像又回到了第一个问题，如何设置好配置，再去生成main_spider.txt（jar）。

我本身没有啥AS基础，只是想多学习，多问问，这样以后自己用也方便些，也涨知识。我看您今天3小时前还更新了，如果您下回再更新，方便的话能不能做个教程，WORD也可以，TXT也可以，当然最好是是视频录像，

联系邮箱：1015710158@qq.com

祝 工作顺利，生活开心。

**Comment by YuanHsing** [comment]
> 您好，因为没有您的联系方式，就这样留言给您了，想向您请教学习几个关于猫影视TV的问题。
> 
> 一、就是如何生动自己的main_spider.txt或者main_spider.jar这个文件，我去catvod的github库那里下载了源码，然后用Android Studio打开，找到spider文件夹，下面很多JAVA文件，教程上应该就是在这里修改，但我没看懂，应该修改哪里，是添加新的文件或是内容，还是删除失效的文件或是内容，还是在哪个文件修改里就可以,很疑惑，这里请求去惑。
> 
> 二、关于首页数据源。您的是2345源，默认的好像是素白白，这个应该也是这个main_spider.txt（jar）决定的，这好像又回到了第一个问题，如何设置好配置，再去生成main_spider.txt（jar）。
> 
> 我本身没有啥AS基础，只是想多学习，多问问，这样以后自己用也方便些，也涨知识。我看您今天3小时前还更新了，如果您下回再更新，方便的话能不能做个教程，WORD也可以，TXT也可以，当然最好是是视频录像，
> 
> 联系邮箱：[1015710158@qq.com](mailto:1015710158@qq.com)
> 
> 祝 工作顺利，生活开心。

main_spider.txt 都是从底下网址获取的，所有资源全部都是小黃瓜大佬維護的
[小黃瓜大佬 維護的影视源](https://c1n.cn/cat)

抱歉 我只会 Ctrl+C 跟 Ctrl+V

建议你可以去猫影视的官方 ISSUE区提问
https://github.com/catvod/CatVodTVSpider/issues

目前猫影视的tg群好像没有开放申请加入，不然应该会有更多大佬可以解决你的问题
希望有帮到你

**Comment by ThorJsbox** [comment]
谢谢
