### ISSUE TITLE
大佬，你的maoo.json怎么用？我试了好几种方法都不能用啊

### ISSUE THREAD

**Issue by tomb003** [YuanHsing/freed#6]
我用的猫影视2.0.7，不管是输入：
https://raw.githubusercontent.com/YuanHsing/freed/master/maoo.json
还是国内镜像：
https://gitee.com/realyoyodadada/freed/raw/master/maoo.json
或是我自己创建的剪贴板：
https://netcut.cn/p/624c68b36da439c0
都只能读取到源列表，但是所有源都不能读取到数据？
是猫影视封了github.com、gitee.com这类文档存储站吗？导致main_spider.txt、custom_spider.jar读取不到？
请教你这maoo.json该怎么用？

**Comment by YuanHsing** [comment]
1. Github:
  Github的配置接口 要改成底下这种格式
  https://github.com/YuanHsing/freed/raw/master/maoo.json
  或是放在你自己的github也可以，那你自己专用的github配接口就可以改成
  https://github.com/tomb003/freed/raw/master/maoo.json

2. Gitee:测试后有问题
  可以把底下这两行

    > "spider":"https://gitee.com/realyoyodadada/CatVodTVSpider/raw/master/jar/custom_spider.jar?raw=true",
    > //"spider": "https://litecucumber.coding.net/p/cat/d/config/git/raw/master/main_spider.txt;md5;2440135559e07083fdc25e7710c843db",

    改成底下设定试试看
    > "spider": "https://litecucumber.coding.net/p/cat/d/config/git/raw/master/main_spider.txt;md5;09f19f293f70bf16a4b266bb5c97ae46"

3. 剪贴板:我测试没有问题
  https://netcut.cn/p/624c68b36da439c0

<hr>
如果你只是单纯的想要看看片，那我会建议你直接用猫影视的官方接口配置，还有大佬维护

选一个用即可，都是一样的

* https://c1n.cn/cat
* http://gg.gg/898900

**Comment by tomb003** [comment]
看了你的回复，我把 https://netcut.cn/p/624c68b36da439c0 里的
"spider":"https://github.com/YuanHsing/OneClickRun/blob/master/xpath/main_spider.txt?raw=true",
删了，把
//"spider": "https://litecucumber.coding.net/p/cat/d/config/git/raw/master/main_spider.txt;md5;2440135559e07083fdc25e7710c843db",
的//注释去掉了，现在用 https://netcut.cn/p/624c68b36da439c0 就能用了。
我怀疑是github、githubusercontent被qiang的问题，我这，这俩网址时断时续，改了dns都没用。

官方的 https://c1n.cn/cat 源太少了，我搜集了很多列表，就大佬你的源列表最好，还有这个：
https://pglblb-1307091970.cos.ap-guangzhou.myqcloud.com/88.json
和这个：
https://pastebin.com/raw/eZewCZ6z
还行，都有大佬保持更新，希望大佬你也能时不时更新，我主用你的源列表。

另外，有个建议，在maoo.json里已经有的源就不用放在maoo2.json里了，要不搜索的时候，maoo2.json里想搜的内容会非常靠后，在电视上要一直按遥控器“下键”滚动很久才能看见，很不方便，一般来说用maoo2.json的时候也不是为了看maoo.json中的内容，术业有专攻，要看正经内容切回maoo.json就行了。
要是猫影视能够支持遥控器上的“翻页键”就好了。
