### ISSUE TITLE
猫影视昨晚突然很多源失效了怎么回事呢？

### ISSUE THREAD

**Issue by hong26** [YuanHsing/freed#7]
如题，很多源失效了，首页也获取不到了。这是什么原因呢？

**Comment by YuanHsing** [comment]
长话短说，猫影视目前更新到2.08版本了，所以做了限制，导致XPATH的功能只有官方的配置接口可以使用!

1. 解决方法1 (可以看所有官方配置源)
 * 猫影视更新到2.08版本
 * 使用官方维护的配置接口 http://gg.gg/898900 或 https://c1n.cn/cat ，择一使用即可

2. 解决方法2 (无法看官方的配置源，但可以看大部份使用者自定义的XPATH网站)
 * 参考Github里的 custom_spider.txt 设定,见底下官方Github网址
   https://github.com/catvod/CatVodTVSpider/tree/master/jar
 * 将 spider 的设定改成下列任一个即可
   *  "spider":"https://litecucumber.coding.net/p/cat/d/config/git/raw/master/custom_spider.txt",
   *  "spider":"https://github.com/catvod/CatVodTVSpider/blob/master/jar/custom_spider.jar?raw=true",

**Comment by hong26** [comment]
> 长话短说，猫影视目前更新到2.08版本了，所以做了限制，导致XPATH的功能只有官方的配置接口可以使用!
> 
> 1. 解决方法1 (可以看所有官方配置源)
> 
> * 猫影视更新到2.08版本
> * 使用官方维护的配置接口 http://gg.gg/898900 或 https://c1n.cn/cat ，择一使用即可
> 
> 2. 解决方法2 (无法看官方的配置源，但可以看大部份使用者自定义的XPATH网站)
> 
> * 猫影视更新到2.08版本(不更新应该也是可以)
> * 参考Github里的 custom_spider.txt 设定,见底下官方Github网址
>   https://github.com/catvod/CatVodTVSpider/tree/master/jar
> * 将 spider 的设定改成下列任一个即可
>   
>   * "spider":"https://litecucumber.coding.net/p/cat/d/config/git/raw/master/custom_spider.txt",
>   * "spider":"https://github.com/catvod/CatVodTVSpider/blob/master/jar/custom_spider.jar?raw=true",

谢谢解答，官方似乎有意不再提供视频源了，刚刚升级2.0.8后使用官方配置接口显示全部已经停用了。
