### ISSUE TITLE
猫影视的源获取不到主页了

### ISSUE THREAD

**Issue by zhousp0914** [YuanHsing/freed#9]
大佬你好，

  你整理的这个猫影视的源真的很好很全，但前几天开始猫影视的源都获取不到主页了，也不能搜索。
我把spider改成以下国内镜像或者gitee上folk的jar文件也都不行。不知道你是否碰到过或知道解决方法呢？
`"spider":"https://litecucumber.coding.net/p/cat/d/config/git/raw/master/custom_spider.txt"`

**Comment by YuanHsing** [comment]
获取不到主页 应该是前几天 猫影视官方GITHUB有更新AppYS的规则所导致https://github.com/catvod/CatVodTVSpider

但 maoo.json 及 maoo2.json 我也有在两天前更新过了，目前大部分的APP影视都可以看没有问题

另外，分别测试底下两个spider设定 都可以用
"spider":"https://github.com/catvod/CatVodTVSpider/blob/master/jar/custom_spider.jar?raw=true",
或是
"spider":"https://litecucumber.coding.net/p/cat/d/config/git/raw/master/custom_spider.txt",

要不要把我的maoo.json或maoo2.json设定 再复制一次试看看?

或是直接用我的设定当配置接口 试试
https://github.com/YuanHsing/freed/raw/master/maoo.json
https://github.com/YuanHsing/freed/raw/master/maoo2.json
